name: run tests

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - main

jobs:
  run_python_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: run tests
        run: uv run pytest
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}

      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-results
          path: allure-results

      - name: generate allure-report
        if: always()
        uses: simple-elf/allure-report-action@v1.15
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report

      - name: Upload allure-report as artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-report
          path: allure-report

  deploy_report:
    needs: run_python_tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download allure-report
        uses: actions/download-artifact@v8
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REQRES_IN_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false
          destination_dir: .